AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  instance-permissions

  SAM Template for instance-permissions Lambda function to retrieve EC2 instance details.

Globals:
  Function:
    Timeout: 30
    LoggingConfig:
      LogFormat: JSON

Resources:
  InstanceDecisionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: instance_permissions/  # Path to the folder with your code
      Handler: app.lambda_handler     # Update to match the entry point in your Python file
      Runtime: python3.13             # Ensure the runtime is correct for your code
      Architectures:
        - x86_64
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - ec2:DescribeInstances
            Resource: '*'             # Allow describing all instances (limit scope if possible)
